---
# handlers file for nginx.domain

- name: restart nginx
  service:
    name: nginx
    enabled: true
    state: restarted

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded